### ISSUE TITLE
format for html in lead for label

### ISSUE THREAD

**Issue by frank-scott** [jbuchbinder/salesforce-wordpress-to-lead#1]
I have tried to implement this change and am not having any luck.  Here is what I am trying to use. Am I missing something?

I have read and agree to the <a href="http://www.nextslideimaging.com/terms-of-use/">Terms & Conditions</a>

Just to clarify, I need the type to be a check box, but the label to contain the text and link above.

**Comment by jbuchbinder** [comment]
To clarify, with this fix, you need to set the "opts" field for a checkbox to "html" to allow HTML-formatted labels.
