### ISSUE TITLE
Additional FIeld Types

### ISSUE THREAD

**Issue by davers714** [jbuchbinder/salesforce-wordpress-to-lead#12]
I love this plug in.

Is there any way to have the following field types be incorporated?

Date

Picklist

Thank you for your help.  I am using this more as an online application form... lots of fields and lots of different data. 

Thanks,

Dave

**Comment by jbuchbinder** [comment]
Picklists are already working as "select" types.

Date selection would probably create a jquery dependency (or another toolkit, if we were to use another one, instead). It's doable, though.

**Comment by davers714** [comment]
My apologies Jeff,

I only see 

Text
Textarea
Hidden

as my options.  Is there an add-on that I need to install to the plugin for that?

Thank you

On Mar 3, 2013, at 6:38 PM, Jeff Buchbinder wrote:

> Picklists are already working as "select" types.
> 
> Date selection would probably create a jquery dependency (or another toolkit, if we were to use another one, instead). It's doable, though.
> 
> —
> Reply to this email directly or view it on GitHub.

David Dobias
dave@geronimoeducation.com
(850) 252-3696

**Comment by jbuchbinder** [comment]
You need to install the lastest git "master" version of the plugin to get the additional benefits of this fork. You can do so by using the Wordpress Plugin Editor, and replacing the contents of salesforce.php with :

https://raw.github.com/jbuchbinder/salesforce-wordpress-to-lead/f17cf360f2b32a5e6eda7d241dcd280f58526f07/salesforce.php

for example, or if you want whatever the bleeding edge development copy is, at the moment:

https://raw.github.com/jbuchbinder/salesforce-wordpress-to-lead/master/salesforce.php

**Comment by davers714** [comment]
Thank you this is great!

On Mar 3, 2013, at 6:46 PM, Jeff Buchbinder wrote:

> You need to install the lastest git "master" version of the plugin to get the additional benefits of this fork. You can do so by using the Wordpress Plugin Editor, and replacing the contents of salesforce.php with :
> 
> https://raw.github.com/jbuchbinder/salesforce-wordpress-to-lead/f17cf360f2b32a5e6eda7d241dcd280f58526f07/salesforce.php
> 
> for example, or if you want whatever the bleeding edge development copy is, at the moment:
> 
> https://raw.github.com/jbuchbinder/salesforce-wordpress-to-lead/master/salesforce.php
> 
> —
> Reply to this email directly or view it on GitHub.

David Dobias
dave@geronimoeducation.com
(850) 252-3696

**Comment by davers714** [comment]
Jeff,

I have had success with text, check box, and text area,

The "select" is showing the arrows, but no options are contained.  

Both of the selection fields have more than 50 options.... could that be an issue?

On Mar 3, 2013, at 6:46 PM, Jeff Buchbinder wrote:

> You need to install the lastest git "master" version of the plugin to get the additional benefits of this fork. You can do so by using the Wordpress Plugin Editor, and replacing the contents of salesforce.php with :
> 
> https://raw.github.com/jbuchbinder/salesforce-wordpress-to-lead/f17cf360f2b32a5e6eda7d241dcd280f58526f07/salesforce.php
> 
> for example, or if you want whatever the bleeding edge development copy is, at the moment:
> 
> https://raw.github.com/jbuchbinder/salesforce-wordpress-to-lead/master/salesforce.php
> 
> —
> Reply to this email directly or view it on GitHub.

David Dobias
dave@geronimoeducation.com
(850) 252-3696

**Comment by jbuchbinder** [comment]
Are you populating the "opts" field?

This plugin, in its current state, is being used in a few production sites. I assure you, when properly configured, it does work.

The "select" widget takes an opts field which is formed by pipe delimited options, with an optional label separated by a ':' character. For example:

`A:1|B:2|C:3`

would produce a select widget containing "A", "B", and "C", mapping to the values 1, 2, and 3, respectively. A simpler form where keys and values are the same would be:

`A|B|C`

which would produce a widget containing "A", "B", and "C".

**Comment by camj1970** [comment]
Can you add the field type url?

**Comment by jbuchbinder** [comment]
Please open another request for that, as this one has already been completed.
