### ISSUE TITLE
Required Select issue

### ISSUE THREAD

**Issue by redone975** [jbuchbinder/salesforce-wordpress-to-lead#13]
I'm currently utilizing the "select" option on some forms as a required input... Here's an example of the options within one drop down:

Please select...|Customer:Customer|Prospective Customer:Prospective Customer|Other:Other

Functionally, it's working great, until I did some usability testing... If the user leaves the default state selected "Please select...", it's passing this as a successful selection... Ideally, this would fire off a "Please select from the list" alert.

**Comment by jbuchbinder** [comment]
It's not a defect. Try something like this:

```
Please select...:|Customer:Customer|Prospective Customer:Prospective Customer|Other:Other
```

Notice the extra `:` character after "Please select...".

**Comment by redone975** [comment]
Perfect... Thanks for the clarification...
