### ISSUE TITLE
Generating all "1" for leads in Salesforce

### ISSUE THREAD

**Issue by bwetterauer** [jbuchbinder/salesforce-wordpress-to-lead#15]
I downloaded the WordPress-to-Lead for Salesforce plugin from GitHub. The one problem I'm having with the version that I downloaded and installed from GitHub is that when testing the form, the results I get in Salesforce show up like this:

First name: 1
Last name: 1
Email: 1
Phone: 1
Zip: 1

Do you know the reason for this?

**Comment by jbuchbinder** [comment]
The patch for #14 was terrible -- it basically broke the entire thing. I'm changing it right now.
