### ISSUE TITLE
wp_options transient data

### ISSUE THREAD

**Issue by derekpiccola** [jbuchbinder/salesforce-wordpress-to-lead#19]
First of all, thanks for the great plugin. 

I downloaded the fork that enables html select tags and I noticed the plugin now rapidly adds huge quantities of transient data to my wp_options table. Roughly 700,000+ rows per day. Enough to overload my hosting's shared mySQL server. As soon as I disable the plugin in Wordpress' admin panel, the rows stop being generated. Please see attached screen.

Again, thanks for the hard work and great plugin!
![capture](https://f.cloud.github.com/assets/5282475/1005474/a92bddec-0abc-11e3-8a97-080f971b6b7a.JPG)

**Comment by jbuchbinder** [comment]
The only part of the plugin which deals with transient data is the captcha portion. I'm going to try to patch it, but if you disable captcha, it won't create those rows.

**Comment by jbuchbinder** [comment]
Apparently, this is also related to a Wordpress bug, involving not garbage collecting transient data:

http://wordpress.stackexchange.com/questions/6602/are-transients-garbage-collected

It's probably a good idea to consider using this plugin, if you're going to use the captcha capability:

http://wordpress.org/plugins/artiss-transient-cleaner/

**Comment by derekpiccola** [comment]
I updated my captcha.php with the raw commit file and the rows are still being added for some reason. Disabling captcha in the Admin settings does do the trick, while not ideal. I also installed the suggested plugin and that does the job of clearing the accumulated transient data. 

Thanks for the quick response, I appreciate it! Are you accepting donations anywhere?

**Comment by jbuchbinder** [comment]
Sure, you can drop me something on [gittip](https://www.gittip.com/jbuchbinder/), or send me an [Amazon Gift Card](https://www.amazon.com/gp/product/B004LLIKVU/gcrnsts) to my email address, `jeffreymbuchbinder [at] gmail`. ;)
