### ISSUE TITLE
Line break after checkbox field

### ISSUE THREAD

**Issue by drew173** [jbuchbinder/salesforce-wordpress-to-lead#2]
When implementing a check field, there is no line break inserted after the check field's label.  So if you have a check field followed by a text field it looks like this:

[X] Checkfieldlabel Textfieldlabel
[**_Text field**_]

**Comment by jbuchbinder** [comment]
It's a CSS issue. I'm adding a CSS class `w2llabel-checkbox-label`, to which you should be able to add `clear: both;` or something similar (or even `margin-bottom: 10px;`) to bump down the next item.
