### ISSUE TITLE
Feature Request: Reply-to email from user

### ISSUE THREAD

**Issue by jasonsee** [jbuchbinder/salesforce-wordpress-to-lead#8]
When submitting a form, have the function salesforce_cc_admin use 'reply-to' with the user's email address, so admins can reply directly to the user, if needed.

**Comment by jbuchbinder** [comment]
It also needs a "sender" address, to not be marked as spam by most mail providers. Patch will be pushed out shortly.

**Comment by jasonsee** [comment]
I'm getting a "Fatal error: Can't use function return value in write context on line 934" when attempting to apply your patch, FYI. Thanks for the patch!
